language: shell
notifications:
  email:
    recipients:
      - ray.ferguson@devendortech.com
os:
  - linux
  - osx
  - windows
# Trusty is 14.04 LTS. 18.04 LTS / beaver is not supported by travis 10/2018
# setting these two options allows faster testing in docker images.
dist: trusty
sudo: false
env:
  matrix:
    - CUSTOM_JDK="openjdk7"
    - CUSTOM_JDK="oraclejdk8"
    # oraclejdk7 is no longer supported by oracle or travis
    # 9 is available on trusty. Please try a newer xcode
    # below if you get newer java working.
    # - CUSTOM_JDK="oraclejdk9"
matrix:
  exclude:
    - os: osx
      env: CUSTOM_JDK="openjdk7"
    - os: osx
      env: CUSTOM_JDK="oraclejdk9"
    - os: windows
      env: CUSTOM_JDK="openjdk7"
    - os: windows
      env: CUSTOM_JDK="oraclejdk9"
addons:
  hosts:
    - travis
  hostname: travis
# pin to xcode9.3. Newer versions use java 10.
osx_image: xcode9.3
git:
  depth: 2
before_install:
  - |-
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      export JAVA_HOME=$(/usr/libexec/java_home)
      export PATH=${JAVA_HOME}/bin:$PATH
      brew update
      brew install ant
      echo "############### SYSINFO ##################"
      sw_vers
    fi
  - |-
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      jdk_switcher use "$CUSTOM_JDK"
      export PATH=$JAVA_HOME/bin:$PATH
      twistd  ftp -r $HOME
      source /etc/os-release
      apt-get update
      apt-get upgade -y -s
      echo "############### SYSINFO ##################"
      echo $PRETTY_NAME
      uname -rp
    fi
  - |-
    if [ "$TRAVIS_OS_NAME" == 'windows' ] ; then
      export JAVA_HOME=`ls -d /c/Program\ Files/Java/jdk1.8.*|head -1`
      export PATH="${JAVA_HOME}/bin:$PATH"
      choco install -i ant
      echo "############### SYSINFO ##################"
      powershell "systeminfo | findstr /C:\"OS\""
    fi
  # useful for troubleshooting.
  - |-
    echo "############### VERSIONS ##################"
    java -version
    javac -version
    ant -version
    unset _JAVA_OPTIONS
# Testing doesn't work so well with odd things in PATH and within bash on travis.
script: |-
   if [ "$TRAVIS_OS_NAME" == "windows" ] ; then
      WJAVA_HOME=$(echo $JAVA_HOME | sed 's#^/c#C:# ; s#/#\\#g')
      cat<<END > build.bat
   @echo on
   call refreshenv
   echo "########## original env ############"
   set
   set "JAVA_HOME=$WJAVA_HOME"
   set CLASSPATH=
   where ant
   REM FOR /F "tokens=*" %%H IN ('where dnvm.cmd') do SET DNXP=%%H
   set "PATH=%JAVA_HOME%/bin;%PATH:C:\tools\ruby25\bin;=%"
   REM set "PATH=%WINDIR%\system32;%WINDIR%;%ChocolateyInstall%\bin;%JAVA_HOME%\bin;%DNXP:dnvm.cmd=%;%XPP:xperf.exe=%"
   echo "############### ENV ##################"
   set
   echo "############### BUILD ##################"
   ant || exit ERRORLEVEL
   echo "############# TEST ###############"
   ant regrtest-travis
   exit ERRORLEVEL
   END
      ./build.bat
   else
      echo "############### ENV ##################"
      env
      echo "############### BUILD ##################"
      ant && echo "############# TEST ###############" && ant regrtest-travis
   fi
