---

notifications:
  email:
    recipients:
      - jython-dev@lists.sourceforge.net

install: 
  - ant

os:
  - linux
  - osx

# setting these two options allows faster testing in docker images.
dist: trusty

sudo: false 

env:
  matrix:
    - CUSTOM_JDK="default"
    - CUSTOM_JDK="openjdk7"
    - CUSTOM_JDK="oraclejdk8"
    # oraclejdk7 is no longer supported on travis, but 9 is
    # Good luck making it work!
    # - CUSTOM_JDK="oraclejdk9"

matrix:
  exclude:
     # On OSX, run with default JDK only.
     - os: osx
       env: CUSTOM_JDK="openjdk7"
     - os: osx
       env: CUSTOM_JDK="oraclejdk8"
     - os: osx
       env: CUSTOM_JDK="oraclejdk9"
     # On Linux, run with specific JDKs only.
     - os: linux
       env: CUSTOM_JDK="default"

addons:
   hosts:
      - travis
   hostname: travis

# newer xcode uses java-10
osx_image: xcode9.3

language: java

before_install:
  - hostname
  - cat /etc/hosts # optionally check the content *after*
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    export JAVA_HOME=$(/usr/libexec/java_home)
    brew update;
    brew install ant ;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    jdk_switcher use "$CUSTOM_JDK" ;
    export PATH=$JAVA_HOME/bin:$PATH ;
    twistd  ftp -r $HOME ;
    fi
  # Travis tests currently work only in java 7 and 8 currently.
  - java -version 2>&1 |grep '"1\.[78]\.' || false 
  - javac -version
  - unset _JAVA_OPTIONS

script: ant && ant regrtest-travis

