notifications:
  email:
    recipients:
      - ray.ferguson@devendortech.com

install:
  - ant

language: java

sudo: false

dist: trusty

os:
  - linux
#  - osx

 
env:
  matrix:
    # - CUSTOM_JDK="default"
    # - CUSTOM_JDK="openjdk7"
    - CUSTOM_JDK="oraclejdk8"
    # - CUSTOM_JDK="openjdk10"

matrix:
  exclude:
     # On OSX, run with default JDK only.
     - os: osx
       env: CUSTOM_JDK="oraclejdk7"
     - os: osx
       env: CUSTOM_JDK="openjdk7"
     - os: osx
       env: CUSTOM_JDK="oraclejdk8"
     - os: osx
       env: CUSTOM_JDK="openjdk10"
     # On Linux, run with specific JDKs only.
     - os: linux
       env: CUSTOM_JDK="default"

before_install:
  # Patch for buffer overflow bug, see https://github.com/travis-ci/travis-ci/issues/5227
  - hostname
  - cat /etc/hosts # optionally check the content *before*
  - #sudo hostname "$(hostname | cut -c1-63)"
  - #sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - hostname
  - cat /etc/hosts # optionally check the content *after*
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ant; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then jdk_switcher use "$CUSTOM_JDK"; export PATH=${JAVA_HOME}/bin:$PATH ; fi
  - javac -version
  - java -version
  - unset _JAVA_OPTIONS
  - unset PYTHON_CFLAGS
  - unset PYTHON_CONFIGURE_OPTS
  - export HOSTNAME=devdr-jython
  - env
  - which python
  - ip -s link show

script: ant && ./dist/bin/jython -m test.regrtest -v --use=network,subprocess test_urllib2net;  ant regrtest-travis  ; ./dist/bin/jython -m test.regrtest -v --use=network,subprocess test_urllib2net

addons:
   hosts:
      devdr-jython

