language: java

notifications:
  email:
    recipients:
      - jython-dev@lists.sourceforge.net

install: ant

os:
  - linux
  - osx
 
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7 
  - default


matrix:
  include:
     # On OSX, run with default JDK only.
     - os: osx
       jdk: default
     # On Linux, run with specific JDKs only.
     - os: linux
       jdk: oraclejdk8
     - os: linux
       jdk: openjdk7
     - os: linux
       jdk: oraclejdk7

before_install:
  # Patch for buffer overflow bug, see https://github.com/travis-ci/travis-ci/issues/5227
  - hostname
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - hostname
  - cat /etc/hosts # optionally check the content *after*
  
script: ant && ant regrtest-travis

