language: java

notifications:
  email:
    recipients:
      - jython-dev@lists.sourceforge.net

install: 
  - ant

os:
  - linux
  - osx

dist: trusty

sudo: false 

env:
  matrix:
    - CUSTOM_JDK="default"
    - CUSTOM_JDK="openjdk7"
    - CUSTOM_JDK="oraclejdk8"
    - CUSTOM_JDK="openjdk9"

matrix:
  exclude:
     # On OSX, run with default JDK only.
     - os: osx
       env: CUSTOM_JDK="oraclejdk7"
     - os: osx
       env: CUSTOM_JDK="openjdk7"
     - os: osx
       env: CUSTOM_JDK="oraclejdk8"
     - os: osx
       env: CUSTOM_JDK="openjdk9"
     # On Linux, run with specific JDKs only.
     - os: linux
       env: CUSTOM_JDK="default"

before_install:
  # Patch for buffer overflow bug, see https://github.com/travis-ci/travis-ci/issues/5227
  # - hostname
  # - cat /etc/hosts # optionally check the content *before*
  #  - sudo hostname "$(hostname | cut -c1-63)"
  # - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  # - hostname
  # - cat /etc/hosts # optionally check the content *after*
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    export JAVA_HOME=$(/usr/libexec/java_home)
    brew update;
    brew install ant; pip install Twisted ;
    brew install gnu-sed;
    alias sed=/usr/local/bin/sed ;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then jdk_switcher use "$CUSTOM_JDK" ; export PATH=$JAVA_HOME:$PATH ; fi
  - sed -i 's#FTP_HOST = .*#FTP_HOST = "ftp://localhost:2121"#' Lib/test/test_urllib2net.py
  - twistd  ftp -r $HOME
  - java -version
  - javac -version


script: ant && ./dist/bin/jython -m test.regrtest -v --use=network,subprocess -e test_urllib2net 

