version: 1.0.{build}
image: Visual Studio 2017
clone_depth: 2
environment:
  matrix:
  - JDK_HOME: C:\Program Files (x86)\Java\jdk1.7.0
  - JDK_HOME: C:\Program Files (x86)\Java\jdk1.8.0
build_script:
- cmd: >-
    set JAVA_HOME=%JDK_HOME%/jre

    set PATH="C:\Program Files (x86)\Java\jdk1.8.0\jre\bin;%JAVA_HOME%/bin;%JDK_HOME%/bin;%PATH%"

    choco install -i ant

    java -version

    javac -version

    ant regrtest-travis

test: off
artifacts:
- path: dist/testreports/TEST*.xml
