version: 1.0.{build}
clone_depth: 2
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1604
build_script:
- sh: ls -l /usr/lib/jvm
