version: 1.0.{build}
image: Visual Studio 2017
clone_depth: 2
environment:
  matrix:
  - JDK_HOME: C:\Program Files (x86)\Java\jdk1.7.0
  - JDK_HOME: C:\Program Files (x86)\Java\jdk1.8.0
build_script:
- cmd: >-
    set JAVA_HOME=%JDK_HOME%/jre

    set PATH=%JAVA_HOME%/bin;%JDK_HOME%/bin;%PATH%

    choco install -i --version=1.9.9 ant

    java -version

    javac -version

    ant
test_script: 
- cmd: ant regrtest-travis
on_finish:
- ps: "$wc = New-Object 'System.Net.WebClient'\nGet-ChildItem \".\\dist\\testresults\" -Filter *.xml |\nForeach-Object {\n$wc.UploadFile(\"https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)\", (Resolve-Path $_))\n}\n"

