version: 1.0.{build}
shallow_clone: true
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  matrix:
    - DESC: ws2012r2 jdk7 x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      JAVA_HOME: C:\Program Files\Java\jdk1.7.0
      require_pass: true
    - DESC: ws2012r2 jdk8 x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0
      require_pass: true
    - DESC: xenial openjdk8 x64
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1604
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      require_pass: true
    - DESC: ws2016 jdk8 x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0
      require_pass: true
    - DESC: bionic openjdk8 x64
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      require_pass: true
    - DESC: xenial openjdk7 x64
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1604
      JAVA_HOME: /usr/lib/jvm/java-7-openjdk-amd64
      require_pass: false
    - DESC: bionic openjdk9 x64
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      JAVA_HOME: /usr/lib/jvm/java-9-openjdk-amd64
      require_pass: false
    - DESC: ws2012r2 jdk8 x86 (32 bit)
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
      require_pass: false
matrix:
  allow_failures:
    - require_pass: false
build_script:
  - cmd: |-
     echo "############# %DESC% ##############"
     REM Tests are sensitive to PATH. test_xmlrpc throws without Dnvm. Launcher and test_os fail
     REM When PATH has some extra thing somewhere in PATH. Not sure what, but minimal works.
     set TERM=dumb
     set CLASSPATH=
     REM choco install -v -y windows-adk
     REM FOR /F "tokens=*" %%G IN ('where wpa') do SET XPP=%%G
     REM FOR /F "tokens=*" %%G IN ('where dnvm.cmd') do SET DNXP=%%G
     REM where perf*
     REM set "PATH=%WINDIR%\system32;%WINDIR%;%ChocolateyInstall%\bin;%JAVA_HOME%\bin;%DNXP:dnvm.cmd=%;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\system32\config\systemprofile\.dnx\bin;"
     echo %DESC% | findstr jdk7 >Nul && choco install -y -i --version=1.9.9 ant || choco install -y -i  ant
     set "PATH=%JAVA_HOME%\bin;%PATH%"
     echo "############### INFO ##################"
     java -version
     javac -version
     ant -version
     systeminfo | findstr /C:"OS"
     echo "############### ENV ##################"
     set
     echo "############### BUILD ##################"
     ant
     echo "############### TEST ##################"
     ant regrtest-travis
  - sh: |-
     echo "############# ${DESC} ##############"
     export PATH="${JAVA_HOME}/bin:$PATH"
     sudo apt-get update
     #sudo apt-get install -y tzdata || true
     #if [ "$APPVEYOR_BUILD_WORKER_IMAGE" == "Ubuntu1604" ] ; then
     #  dpkg-reconfigure tzdata ; #fi
     sudo apt-get install ant
     unset JAVA_TOOL_OPTIONS
     echo "############### INFO ##################"
     java -version
     javac -version
     source /etc/os-release
     echo $PRETTY_NAME
     uname -rp
     echo "############### ENV ##################"
     env
     echo "############### BUILD ##################"
     ant -version
     ant
     echo "############### TEST ##################"
     ant regrtest-travis
notifications:
  - provider: Email
    to:
      - ray.ferguson@devendortech.com
    # - jython-dev@lists.sourceforge.net
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
on_finish:
  - ps: >-
     $wc = New-Object 'System.Net.WebClient'

     Get-ChildItem .\dist\testreports -Filter *.xml |

     Foreach-Object {
     $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)",
     (Resolve-Path .\dist\testreports\$_))
     }
  - sh: >-
      find "$APPVEYOR_BUILD_FOLDER/dist/testreports" -type f -name 'TEST*.xml'
      -print0 | xargs -0 -I '{}' curl -F 'file=@{}'
      "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"
