version: 1.0.{build}
image: Visual Studio 2017
environment:
  matrix:
  - JDK_HOME: C:\Program Files (x86)\Java\jdk1.7.0
  - JDK_HOME: C:\Program Files (x86)\Java\jdk1.8.0
build_script:
- sh: >-
    choco install -i ant

    export JAVA_HOME="${JDK_HOME}/jre"

    export PATH="${JAVA_HOME}/bin:${JDK_HOME}/bin:$PATH"

    ant regrtest-travis
test: off
artifacts:
- path: dist/testreports/TEST*.xml
