version: 1.0.{build}
image: Visual Studio 2017
clone_depth: 2
environment:
  matrix:
  - JDK_HOME: C:\Program Files (x86)\Java\jdk1.7.0
  - JDK_HOME: C:\Program Files (x86)\Java\jdk1.8.0
build_script:
- cmd: >-
    set JAVA_HOME=%JDK_HOME%/jre

    set PATH=%JAVA_HOME%/bin;%JDK_HOME%/bin;%PATH%

    choco install -i --version=1.9.9 ant

    java -version

    javac -version

    ant
test_script: 
- cmd: ant regrtest-travis
notifications:
- provider: Email
  to:
  - ray.ferguson@devdendortech.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
on_finish:
- ps: >-

    $wc = New-Object 'System.Net.WebClient'



    Get-ChildItem ".\dist\testresults" -Filter *.xml |



    Foreach-Object {
     $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $_))
    }    
